<?xml version="1.0" ?>

<!DOCTYPE calDigi [
<!ELEMENT calDigi (section)* >
<!ATTLIST calDigi cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--    GLAST profile bias correction constants as of Glastrelease v4r4 for 
        2+ GeV 0.3-1. cos(incident angle)
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<calDigi cvs_Header="$Header$"
         cvs_Revision="$Revision$">

    <section name="profileBias">  CAL properties
	<item name="CosThetaLimit"     value="0.3"> </item>
	<item name="BiasParNb"       value="9"> </item>
  <item name="CosThetaParNb"     value="3"> </item>
	<item name="bias8"     value="0.452359"> </item>
	<item name="bias7"     value="-0.604589"> </item>
  <item name="bias6"     value="0.273117"> </item>
	<item name="bias5"     value="-0.0962898"> </item>
	<item name="bias4"     value="0.118555"> </item>
  <item name="bias3"     value="-0.0709624"> </item>
	<item name="bias2"     value="0.0145653"> </item>
	<item name="bias1"     value="-.0271244"> </item>
  <item name="bias0"     value="0.0187272"> </item>
    </section>

</calDigi>
