<?xml version="1.0" ?>

<!DOCTYPE calDigi [
<!ELEMENT calDigi (section)* >
<!ATTLIST calDigi cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--    GLAST digi constants
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<calDigi cvs_Header="$Header$"
         cvs_Revision="$Revision$">

    <section name="cal">  CAL properties
	<item name="ePerMeVinDiode"     value="2.77e5"> MeV 1e6/3.6</item>
    </section>
    <section name="onePlusExpDigi">  digi properties
	<item name="offset"     value="0.88"> constant offset</item>
	<item name="scaleExponential"     value="0.30"> scale factor on exponential</item>
	<item name="scaleExponent"     value="1.818"> scale factor on exponent</item>
	<item name="scaleTurnoverExponential"     value="0.05"> scale factor Turnover on exponential</item>
	<item name="scaleTurnoverExponent"     value="-32.6"> scale factor Turnover on exponent</item>
    </section>

</calDigi>
