<?xml version = '1.0' encoding = 'UTF-8'?>
<!DOCTYPE calCalib [<!--
   $Header$

   /**  @file       calCalib_v2r3.dtd
        @authors    J. Bogart

        dtd for CAL calibration data types

    */

 -->

<!-- 
   Overall structure is some header information followed by
   a sequence of tower data.  Tower data is made up
   of layer data, in turn made up of data for individual
   crystals, which consists of data for (1 or 2, depending
   on calibration type) faces.  

   The header information comes in two parts:
     "generic" is relevant to any sort of calibration data,
               not just that from the CAL, such as the
               name of the instrument being calibrated.
               See further comments above the generic element
               declaration
     "dimension" contains all the parameters necessary to figure 
               out which data goes with which hardware entity.
               See further comments above the dimension element
               declaration
  -->  

<!ELEMENT calCalib (generic, dimension, dac*, xpos?, tower* ) >
       
<!-- Container for all the header/metadata type information to be
     included here.  Complete metadata will be found in the calibration
     MySQL database. 

     Description of attributes:

            instrument    - one of "flight", "EM", etc.  Could also
                            be implemented as enumeration rather than
                            NMTOKEN
            timestamp     - when the file was written (date and time)
            calType       - one of "TKRBadStrips", "CALLightAttenuation",
                            etc.
            formatVersion - sufficient versioning information so that
                            software attempting to read the file can
                            determine if it supports this version. 
                            [Might get rid of this here and just keep
                            it in the MySQL metadata table]
            creator       - script or program creating calibration data
 -->
<!ELEMENT  generic  (inputSample?) >
<!ATTLIST generic  
   instrument  (LAT | BFEM | BTEM | EM | EM2 | CU) #REQUIRED
   timestamp   CDATA #REQUIRED
   calibType (CAL_LightAtt | CAL_LightAsym | CAL_LightYield |
              CAL_Ped | CAL_ElecGain | CAL_IntNonlin | CAL_DiffNonlin |
              CAL_MuSlope | CAL_Asym | CAL_MevPerDac | CAL_TholdCI |
              CAL_TholdMuon)    #REQUIRED
   DTDVersion  NMTOKEN "v2r3"       
   fmtVersion  NMTOKEN #REQUIRED
   creator     CDATA #IMPLIED >

<!-- Description of events used as input to the procedure 
     Start- and stop-times should be timestamps of earliest and
     latest events included in sample.
     inputSample is (for now) optional.
-->
<!ELEMENT inputSample (#PCDATA) >
<!ATTLIST inputSample  startTime CDATA #REQUIRED
                       stopTime  CDATA #REQUIRED
                       triggers  NMTOKENS #REQUIRED 
                       source    NMTOKENS #REQUIRED
                       mode      NMTOKEN  #REQUIRED>

<!-- In many cases calibration is done per range: LEX8 is low-energy 
   (= large) diode, x8 amplification; LEX1 is low-energy, low amplification.
   Similarly have HEX8, HEX1 for high-energy (small) diode.
   Unfortunately can't use parameter entities since they aren't allowed
   when the dtd is literally included in an xml file, something
   we'd like to support.
  -->

<!-- For light asymmetry may lump together amplifications (and by
  definition one set of constants applies to both crystal ends, since
  constants quantify *asymmetry*), so have a set of constants per
  diode-type -->

<!-- Describe how the data is dimensioned:
        number of tower rows
        number of tower columns
        number of calorimeter layers
        number of crystals in a layer ("columns")
        number of faces      (mostly 2; 1 for light asymmetry data)
        number of ranges     (fixed at 4? for now just default to 4) 
        number of sets of dac settings (mostly 0)
        number of xpos elements.  Can only be 0 or 1
        exact    may be "true" or "false".  If "true", above information
                 may be mutliplied to compute total number of innermost
                 elements (e.g., calPed)

   Use the following conventions to determine which data element 
   corresponds to a particular physical crystal, optional face and
   gain range:
       * Tower number is computed from row and column as
                 tower = column + (nCol)*row
       * The data can be viewed as a 5-dimensional array where
         the indices from most- to least-significant are
              tower
              layer
              xtal   (often called "column" in calorimeter code)
              face
              range
         So the first two data elements will correspond to 
           (tower=0,layer=0, xtal=0, face=0, range=0)
           (tower=0,layer=0, xtal=0, face=0, range=1)
 
         The total number of data elements (for the default
         case, with exact = "true") is just
                nRow*nCol*nLayer*nXtal*nFace*nRange

 -->
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension nRow NMTOKEN  #REQUIRED
                    nCol NMTOKEN  #REQUIRED
                    nLayer NMTOKEN #REQUIRED
                    nXtal  NMTOKEN #REQUIRED
                    nFace  NMTOKEN #REQUIRED
                    nRange NMTOKEN "4"      
                    nDacCol NMTOKEN "0" 
                    nXpos  (0 | 1) "0"
                    exact  (true | false) "true" >

<!-- For those calibrations involving setting a dac, keep track of
    settings.  Expect one set per range where used; else 0. Number 
    should match value of dimension attribute nDacCol  -->
<!ELEMENT dac EMPTY>
<!ATTLIST dac range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
          values NMTOKENS #REQUIRED
          error  NMTOKEN  #IMPLIED >   <!-- for now.  May want default -->

<!ELEMENT xpos EMPTY>
<!ATTLIST xpos values NMTOKENS #REQUIRED>

<!ELEMENT tower (layer*) >
<!ATTLIST tower iRow NMTOKEN #REQUIRED
                iCol NMTOKEN #REQUIRED 
                hwserial NMTOKEN "-1" >

<!ELEMENT layer (xtal*) >
<!ATTLIST layer iLayer NMTOKEN #REQUIRED>

<!ELEMENT xtal (face, face?) >
<!ATTLIST xtal iXtal NMTOKEN #REQUIRED>

<!-- each face has data for all four ranges, ordered by range number -->
<!ELEMENT face (calPed* | calGain* | muSlope* | lightAsym* | intNonlin*
                        | mevPerDac* | tholdCI* | tholdMuon*
                        | asym* ) >
<!ATTLIST face end (NEG | POS | NA) #REQUIRED >


<!ELEMENT calPed  EMPTY>
<!ATTLIST calPed  range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED
                  cos NMTOKEN "2" >

<!ELEMENT calGain EMPTY>
<!ATTLIST calGain range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  avg NMTOKEN #REQUIRED
                  sig NMTOKEN #REQUIRED>

<!ELEMENT muSlope EMPTY>
<!ATTLIST muSlope range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                  slope NMTOKEN #REQUIRED
                  error NMTOKEN "0.0" >

<!ELEMENT lightAsym EMPTY>
<!ATTLIST lightAsym diode (LE | HE) #REQUIRED
                    values NMTOKENS #REQUIRED
                    error NMTOKEN #REQUIRED >

<!ELEMENT intNonlin EMPTY>
<!ATTLIST intNonlin range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                    values NMTOKENS #REQUIRED
                    sdacs NMTOKENS  #IMPLIED
                    error NMTOKEN   #REQUIRED >

<!-- Some of mevPerDac information is per-crystal, some is per face.  So
     <mevPerDac> is identified by tower/layer/crystal and contains two
     <bigSmall> elements for the per-face information. 
 -->
<!ELEMENT mevPerDac (bigSmall, bigSmall) >
<!ATTLIST mevPerDac bigVal NMTOKEN #REQUIRED
                    bigSig NMTOKEN #REQUIRED
                    smallVal NMTOKEN #REQUIRED
                    smallSig NMTOKEN #REQUIRED
>
<!ELEMENT bigSmall EMPTY>
<!ATTLIST bigSmall  end (NEG | POS) #REQUIRED
                    bigSmallRatioVals NMTOKENS #REQUIRED
                    bigSmallRatioSigs NMTOKENS #REQUIRED
>

<!ELEMENT asym EMPTY>
<!ATTLIST asym bigVals NMTOKENS #REQUIRED
               bigSigs NMTOKENS #REQUIRED
               smallVals  NMTOKENS #REQUIRED
               smallSigs  NMTOKENS #REQUIRED
               NsmallPbigVals NMTOKENS #REQUIRED
               NsmallPbigSigs NMTOKENS #REQUIRED
               PsmallNbigVals NMTOKENS #REQUIRED
               PsmallNbigSigs NMTOKENS #REQUIRED
>

<!-- Some of tholdCI information is per-crystal-face, some is per range.  So
     <tholdCI> is identified by tower/layer/crystal/face and contains up
       to 4 tholdCIRange elements for per-range information
 -->
<!ELEMENT tholdCI (tholdCIRange, tholdCIRange?, tholdCIRange?, tholdCIRange?) >
<!ATTLIST tholdCI FLEVal NMTOKEN #REQUIRED
                  FLESig NMTOKEN #REQUIRED
                  FHEVal NMTOKEN #REQUIRED
                  FHESig NMTOKEN #REQUIRED
                  LACVal NMTOKEN #REQUIRED
                  LACSig NMTOKEN #REQUIRED
>

<!ELEMENT tholdCIRange EMPTY>
<!ATTLIST tholdCIRange range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                       pedVal NMTOKEN #REQUIRED
                       pedSig NMTOKEN #REQUIRED
                       ULDVal NMTOKEN #REQUIRED
                       ULDSig NMTOKEN #REQUIRED
>

<!-- Some of tholdMuon information is per-crystal-face, some is per range.  So
     <tholdMuon> is identified by tower/layer/crystal/face and contains up
       to 4 tholdMuonRange elements for per-range information
 -->
<!ELEMENT tholdMuon (tholdMuonRange, tholdMuonRange?, tholdMuonRange?, 
                     tholdMuonRange?) >
<!ATTLIST tholdMuon FLEVal NMTOKEN #REQUIRED
                    FLESig NMTOKEN #REQUIRED
                    FHEVal NMTOKEN #REQUIRED
                    FHESig NMTOKEN #REQUIRED >

<!ELEMENT tholdMuonRange EMPTY>
<!ATTLIST tholdMuonRange range (LEX8 | LEX1 | HEX8 | HEX1) #REQUIRED
                         pedVal NMTOKEN #REQUIRED
                         pedSig NMTOKEN #REQUIRED
>

]>

<calCalib>
  <generic creator="myname" fmtVersion="v2r3" timestamp="2007-04-11-16:27" calibType="CAL_IntNonlin" instrument="LAT" />
  <dimension nRange="4" nXpos="0" nLayer="8" nFace="2" nCol="4" exact="false" nDacCol="0" nXtal="12" nRow="4" />
  <tower iRow="0" iCol="0" >
<!--tem number = 0, module = FM104-->    <layer iLayer="0" >
<!--layer name = X0-->      <xtal iXtal="0" >
        <face end="NEG" >
          <intNonlin error="0.10" values="0.00 23.46 93.44 163.87 232.61 301.63 371.27 441.41 510.91 580.37 649.99 720.88 1119.83 1685.96 2258.35 2451.03 2644.09 2840.51 3033.85 3230.41 3427.25" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.02" />
          <intNonlin error="0.10" values="0.00 2.62 13.04 23.41 33.64 43.90 54.18 64.47 74.83 103.48 187.49 272.58 359.20 446.18 533.57 621.41 730.19 908.01 1088.76 1271.06 1454.10 1637.66 1821.59 2005.60 2190.03 2374.38 2558.72 2743.01 2927.29 3111.27 3295.25 3387.01 3433.21 3479.01 3524.91 3570.63 3616.67 3662.61 3708.47 3754.39 3800.33 3879.95" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2687.00 2742.46" />
          <intNonlin error="0.10" values="0.00 17.55 70.01 121.99 174.70 226.00 278.22 334.40 390.16 443.88 497.03 550.67 850.00 1272.52 1694.63 2117.79 2541.09 2681.99 2824.09 2966.73 3106.33 3248.15 3390.81 3446.71" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 384.00 390.27" />
          <intNonlin error="0.10" values="0.00 1.97 9.80 17.62 25.38 33.17 41.53 49.58 57.47 79.20 142.06 204.95 268.06 331.29 394.53 457.73 535.90 663.13 789.41 916.17 1042.92 1169.61 1296.22 1422.65 1549.30 1675.85 1802.40 1928.95 2055.44 2181.57 2307.42 2432.61 2557.93 2683.92 2811.16 2935.99 3061.29 3179.59 3300.56 3432.50 3527.20 3558.74 3590.04 3621.28 3652.74 3683.94 3715.24 3746.40 3777.62 3808.76 3872.46" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3936.46" />
        </face>
        <face end="POS" >
          <intNonlin error="0.10" values="0.00 23.23 93.63 162.30 232.94 304.27 373.93 444.35 515.16 586.48 656.91 727.50 1130.44 1703.25 2280.80 2472.60 2669.76 2865.76 3063.40 3259.13 3454.72 3642.50" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.00 303.36" />
          <intNonlin error="0.10" values="0.00 2.64 13.26 23.53 34.10 44.54 55.04 65.63 76.07 105.14 190.42 276.53 364.13 451.95 540.29 628.93 738.99 918.19 1100.22 1283.84 1468.37 1653.29 1838.30 2023.58 2208.96 2394.61 2579.99 2765.21 2950.48 3135.57 3320.36 3366.52 3412.64 3459.00 3505.20 3551.44 3597.52 3643.82 3689.78 3736.04 3781.90 3865.00" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2367.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2712.99" />
          <intNonlin error="0.10" values="0.00 17.66 70.59 123.22 175.76 228.38 281.40 334.12 390.87 445.80 500.32 553.41 856.22 1281.80 1707.90 2133.49 2560.08 2702.16 2844.12 2986.02 3129.08 3272.58 3443.00" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 387.00" />
          <intNonlin error="0.10" values="0.00 1.98 9.80 17.58 25.45 33.16 41.32 49.68 57.72 79.56 143.11 206.48 270.04 333.58 397.29 461.05 539.73 667.08 793.56 921.41 1048.81 1176.35 1303.89 1431.64 1559.23 1686.67 1813.55 1940.34 2066.93 2193.63 2320.47 2447.21 2574.02 2701.01 2827.86 2954.32 3079.44 3203.45 3331.75 3456.71 3540.69 3572.49 3603.81 3634.99 3665.93 3696.73 3727.89 3759.11 3790.21 3820.77 3871.43" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3924.05" />
        </face>
      </xtal>
      <xtal iXtal="1" >
        <face end="NEG" >
          <intNonlin error="0.10" values="0.00 22.73 90.43 159.61 228.45 297.45 366.47 435.86 505.13 575.95 644.71 713.58 1109.80 1673.10 2241.56 2432.01 2626.39 2819.53 3012.71 3204.85 3399.90 3489.47" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.00 295.35" />
          <intNonlin error="0.10" values="0.00 2.55 12.75 23.04 33.22 43.48 53.77 64.27 74.51 103.10 186.93 271.97 358.38 444.95 531.99 619.35 727.92 905.08 1084.92 1266.58 1449.51 1632.70 1816.34 2000.14 2184.27 2368.52 2552.62 2736.49 2920.20 3103.73 3287.31 3379.00 3425.04 3470.50 3516.32 3562.30 3607.82 3653.90 3699.72 3745.46 3791.18 3870.72" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2687.00 2742.67" />
          <intNonlin error="0.10" values="0.00 17.14 68.73 120.34 172.27 223.71 276.10 332.79 386.19 440.11 493.33 545.45 843.46 1264.06 1684.59 2106.28 2527.44 2667.81 2808.73 2948.73 3090.35 3230.99 3372.09 3494.61" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 384.00 397.89" />
          <intNonlin error="0.10" values="0.00 1.95 9.67 17.42 25.06 32.97 41.22 49.22 57.16 78.83 141.60 204.63 267.69 330.87 393.92 457.18 535.27 661.95 788.50 914.94 1041.52 1168.25 1294.89 1421.48 1548.27 1674.87 1801.52 1928.11 2054.51 2180.92 2306.89 2432.87 2558.64 2684.31 2810.21 2936.08 3061.70 3186.19 3311.41 3434.63 3522.22 3553.56 3584.26 3615.18 3646.38 3677.34 3708.30 3739.56 3772.28 3807.10 3866.00" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3925.13" />
        </face>
        <face end="POS" >
          <intNonlin error="0.10" values="0.00 23.42 93.85 163.44 233.08 303.47 373.95 443.39 513.00 583.55 653.49 724.51 1124.90 1695.69 2270.87 2463.71 2658.89 2856.17 3048.85 3244.61 3317.89" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 277.99" />
          <intNonlin error="0.10" values="0.00 2.61 13.07 23.48 33.85 44.30 54.65 65.10 75.62 104.61 189.54 275.54 362.87 450.45 538.70 627.34 736.92 916.10 1097.98 1281.65 1465.86 1650.51 1835.46 2020.43 2205.78 2391.01 2576.19 2761.47 2946.40 3131.34 3316.25 3408.68 3454.82 3500.82 3547.22 3593.28 3639.20 3685.42 3731.44 3777.38 3823.48 3878.04" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2687.00 2724.87" />
          <intNonlin error="0.10" values="0.00 17.32 68.91 121.42 173.36 225.19 277.29 332.41 389.30 443.52 496.26 549.88 850.18 1272.70 1695.95 2118.38 2542.80 2683.72 2825.64 2965.84 3108.92 3250.20 3398.44" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 384.79" />
          <intNonlin error="0.10" values="0.00 1.95 9.68 17.50 25.24 33.03 41.40 49.64 57.58 79.40 142.60 206.00 269.30 332.76 396.33 459.85 538.33 665.72 792.50 919.83 1047.34 1174.58 1301.60 1428.71 1556.02 1683.35 1810.63 1938.14 2065.22 2192.03 2318.31 2444.14 2570.01 2696.38 2823.49 2950.88 3076.23 3198.71 3325.31 3442.10 3536.64 3567.82 3599.42 3629.88 3665.66 3701.40 3732.78 3763.80 3795.06 3826.36 3869.22" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3914.82" />
        </face>
      </xtal>
      <xtal iXtal="2" >
        <face end="NEG" >
          <intNonlin error="0.10" values="0.00 23.09 92.27 162.18 232.13 301.23 371.47 441.01 511.21 581.52 651.39 721.90 1122.14 1690.84 2264.47 2455.89 2650.39 2846.85 3041.25 3237.67 3433.41 3537.03" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.00 296.47" />
          <intNonlin error="0.10" values="0.00 2.60 12.95 23.28 33.52 43.78 54.13 64.42 74.82 103.46 187.35 272.24 358.57 445.29 532.47 620.02 728.41 905.71 1086.00 1267.85 1451.43 1635.55 1820.14 2004.98 2190.30 2375.51 2560.85 2746.07 2931.20 3116.13 3300.97 3393.43 3439.71 3485.79 3531.87 3577.71 3624.25 3670.39 3716.57 3762.89 3808.81 3863.51" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2687.00 2725.12" />
          <intNonlin error="0.10" values="0.00 17.86 70.84 123.51 175.79 228.34 280.62 334.88 391.37 447.50 501.27 554.38 858.23 1284.05 1710.76 2137.40 2564.96 2707.30 2851.10 2994.06 3136.60 3280.50 3422.58 3562.34" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 384.00 399.74" />
          <intNonlin error="0.10" values="0.00 1.96 9.75 17.46 25.24 33.01 41.17 49.35 57.35 79.16 142.25 205.23 268.38 331.71 394.99 458.25 536.67 663.58 790.12 916.91 1044.10 1171.13 1297.77 1424.51 1551.24 1678.01 1804.87 1931.64 2058.12 2184.49 2310.53 2435.99 2561.74 2687.67 2813.83 2939.73 3064.70 3188.64 3314.62 3439.43 3569.33 3585.21 3617.43 3648.63 3679.45 3710.65 3741.41 3772.11 3803.13 3834.09 3885.35" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3903.00 3955.98" />
        </face>
        <face end="POS" >
          <intNonlin error="0.10" values="0.00 23.03 91.81 161.51 231.84 300.72 371.83 441.69 512.34 582.62 652.65 723.71 1124.73 1696.15 2271.91 2465.26 2657.80 2854.80 3051.34 3245.06 3442.52 3505.14" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.00 293.07" />
          <intNonlin error="0.10" values="0.00 2.56 12.74 23.09 33.39 43.75 54.17 64.55 75.00 103.76 188.09 273.51 360.12 447.37 535.04 623.13 732.28 910.59 1091.80 1275.08 1459.81 1645.18 1830.76 2016.71 2202.97 2389.44 2575.69 2762.09 2948.19 3134.38 3320.46 3367.02 3413.44 3459.94 3506.12 3552.76 3599.40 3645.72 3692.14 3738.54 3785.34 3872.44" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2367.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2714.56" />
          <intNonlin error="0.10" values="0.00 17.44 69.94 122.56 175.19 227.77 282.69 340.53 394.51 449.44 502.63 556.36 860.22 1288.08 1716.94 2146.46 2576.17 2862.12 3006.46 3150.64 3293.64 3437.68 3581.78 3675.02" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 320.00 336.00 352.00 368.00 384.00 400.00 410.35" />
          <intNonlin error="0.10" values="0.00 1.93 9.73 17.60 25.38 33.61 41.85 49.97 57.88 79.79 143.16 206.70 270.39 334.08 398.00 461.82 540.65 669.17 796.86 924.25 1052.09 1180.20 1308.04 1436.06 1563.77 1691.64 1819.26 1946.81 2074.22 2201.51 2328.63 2455.62 2582.76 2710.08 2837.22 2964.27 3090.34 3216.11 3344.75 3464.27 3492.09 3523.59 3554.71 3585.85 3617.21 3648.73 3679.71 3711.23 3744.89 3780.07 3855.27" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3519.00 3551.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3875.40" />
        </face>
      </xtal>
      <xtal iXtal="3" >
        <face end="NEG" >
          <intNonlin error="0.10" values="0.00 23.03 91.74 162.17 230.24 300.91 370.71 441.26 511.96 581.64 651.65 721.99 1122.68 1690.60 2264.16 2651.66 2846.48 3041.88 3236.66 3429.92 3624.40 3677.04" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 224.00 240.00 256.00 272.00 288.00 304.00 308.33" />
          <intNonlin error="0.10" values="0.00 2.55 12.77 23.01 33.37 43.77 54.16 64.55 74.89 103.70 187.97 273.21 359.95 446.84 534.30 622.21 731.14 908.49 1089.04 1271.20 1454.98 1638.91 1823.44 2008.12 2193.17 2378.26 2563.22 2748.16 2932.94 3117.56 3302.09 3394.24 3440.58 3486.62 3532.68 3578.64 3624.60 3670.82 3716.78 3762.58 3808.34 3881.44" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2687.00 2738.12" />
          <intNonlin error="0.10" values="0.00 17.30 69.26 120.68 172.81 225.94 278.53 332.61 389.30 443.93 496.87 550.77 852.83 1276.78 1702.37 2126.78 2553.41 2837.83 2978.79 3121.51 3263.84 3405.75 3547.89 3693.55" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 320.00 336.00 352.00 368.00 384.00 400.00 416.40" />
          <intNonlin error="0.10" values="0.00 1.90 9.59 17.33 25.01 32.87 41.03 49.13 57.02 78.77 141.66 204.51 267.58 330.61 393.84 457.03 535.18 661.63 787.86 914.27 1040.98 1167.77 1294.51 1421.01 1547.63 1674.22 1800.70 1927.01 2053.13 2179.68 2306.09 2431.25 2556.60 2684.36 2808.97 2930.31 3049.50 3173.14 3304.46 3430.98 3555.91 3587.35 3618.55 3649.69 3680.67 3711.85 3743.01 3774.01 3805.09 3836.31 3883.97" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3903.00 3951.85" />
        </face>
        <face end="POS" >
          <intNonlin error="0.10" values="0.00 23.18 92.36 162.06 232.17 302.07 371.92 442.47 513.04 583.59 653.24 724.05 1125.46 1697.86 2273.94 2466.81 2664.55 2860.61 3055.35 3252.03 3450.47 3618.77" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 208.00 224.00 240.00 256.00 272.00 288.00 301.57" />
          <intNonlin error="0.10" values="0.00 2.60 12.97 23.37 33.81 44.18 54.75 65.18 75.67 104.62 189.78 275.88 363.49 451.23 539.63 628.38 738.31 917.68 1099.47 1282.92 1466.70 1651.08 1835.63 2020.24 2205.14 2390.10 2574.94 2759.82 2944.63 3129.17 3313.86 3359.99 3405.91 3451.93 3498.11 3544.35 3590.39 3636.29 3682.69 3728.27 3774.55 3842.89" range="LEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2367.00 2399.00 2431.00 2463.00 2495.00 2527.00 2559.00 2591.00 2623.00 2655.00 2702.25" />
          <intNonlin error="0.10" values="0.00 17.19 68.57 120.78 173.14 225.25 278.84 335.57 389.82 444.07 497.95 551.06 851.73 1275.47 1700.42 2124.51 2549.84 2691.80 2833.52 2976.66 3119.52 3260.52 3402.62 3517.64" range="HEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 240.00 288.00 304.00 320.00 336.00 352.00 368.00 384.00 396.95" />
          <intNonlin error="0.10" values="0.00 1.94 9.69 17.51 25.15 33.30 41.58 49.60 57.59 79.35 142.63 205.89 269.07 332.61 396.08 459.70 538.12 665.87 792.70 920.40 1047.36 1173.61 1300.17 1426.72 1553.54 1680.45 1807.49 1934.63 2062.22 2189.97 2316.37 2440.19 2563.45 2690.47 2823.52 2943.05 3060.55 3185.98 3313.05 3443.76 3537.34 3568.72 3600.20 3631.44 3662.58 3693.86 3725.20 3756.58 3787.74 3818.86 3862.12" range="HEX1" sdacs="0.00 2.00 10.00 18.00 26.00 34.00 42.00 50.00 58.00 80.00 144.00 208.00 272.00 336.00 400.00 464.00 543.00 671.00 799.00 927.00 1055.00 1183.00 1311.00 1439.00 1567.00 1695.00 1823.00 1951.00 2079.00 2207.00 2335.00 2463.00 2591.00 2719.00 2847.00 2975.00 3103.00 3231.00 3359.00 3487.00 3583.00 3615.00 3647.00 3679.00 3711.00 3743.00 3775.00 3807.00 3839.00 3871.00 3915.48" />
        </face>
      </xtal>
      <xtal iXtal="4" >
        <face end="NEG" >
          <intNonlin error="0.10" values="0.00 23.17 92.00 161.04 229.21 297.79 367.93 436.51 505.37 574.60 644.29 713.92 1108.95 1670.94 2236.21 2616.61 2811.15 3003.17 3197.17 3390.61 3582.23 3683.01" range="LEX8" sdacs="0.00 2.00 8.00 14.00 20.00 26.00 32.00 38.00 44.00 50.00 56.00 62.00 96.00 144.00 192.00 224.00 240.00 256.00 272.00 288.00 304.00 312.42" />