<?xml version="1.0" ?>

<!DOCTYPE AcdGeometry [
<!ELEMENT AcdGeometry (section)* >
<!ATTLIST AcdGeometry cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--      GLAST bfem ACD constants
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<AcdGeometry cvs_Header="$Header$"
            cvs_Revision="$Revision$">

     <section name="acd">  ACD properties
        <item name="num_side_tiles" value="2">      Number of A/C side tiles (per side) </item>
     </section>

     <section name="xgt"> XGT properties all values in mm
	<item name="numXGTs"	    value="4"> number of XGTs </item>
	<item name="ids"	    value="{2011, 2001, 2000, 2010}"> </item>
	<item name="width"	    value="{50.0, 50.0, 50.0, 50.0}"> length of XGTs </item>
	<item name="height"	    value="{50.0, 50.0, 50.0, 50.0}"> width of XGTs </item>
	<item name="length"	    value="{100.0, 100.0, 100.0, 100.0}"> thickness of XGTs </item>
	<item name="x_center"	    value="{123.74, 123.74, -123.74, -123.74}"> x center </item>
	<item name="y_center"	    value="{123.74, -123.74, -123.74, 123.74}"> y center </item>
	<item name="z_center" 	    value="{696.7, 696.7, 696.7, 696.7}"> </item>		
	<item name="rotation"	    value="{45.0, -45.0, 45.0, -45.0}"> number of degrees to rotate the XGTs about z-axis </item>
     </section>

     <section name="acdTop"> ACD top tile properties, lengths in mm
     	<item name="numTiles"    value="4"> Number of top tiles </item>
	<item name="ids"	    value="{11,10,0,1}"> </item>
	<item name="xlen"	    value="{204.0, 204.0, 204.0, 204.0}"> </item>
	<item name="ylen"	    value="{204.0, 204.0, 204.0, 204.0}"> </item>
	<item name="zlen"	    value="{10.0, 10.0, 10.0, 10.0}"> </item>
 	<item name="x_center"	    value="{106.5, -106.5, -106.5, 106.5}"> </item>
	<item name="y_center"	    value="{104.5, 104.5, -104.5, -104.5}"> </item>
	<item name="z_center"	    value="{565.7, 565.7, 565.7, 565.7}"> </item>
    </section>

    <section name="acdSide"> ACD side tile properties
	<item name="ids"  	value="{300,310,100,110,200,210,400,410}"> in the order the tiles are built </item>
        <item name="xlen"	value="{1.0,1.0,1.0,1.0,422.0,440.0,422.0,440.0}"> </item>
        <item name="ylen"	value="{422.0,440.0,422.0,440.0,1.0,1.0,1.0,1.0}"> </item>
        <item name="zlen"	value="{300.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0}"> </item>
        <item name="x_center"	value="{216.5,226.0,-216.5,-226.0,5.0,5.0,5.0,5.0}"> </item>
        <item name="y_center"	value="{5.0,5.0,5.0,5.0,-216.5,-226.0,216.5,226.0}"> </item>
        <item name="z_center"	value="{448.7,172.9,448.7,172.9,448.7,172.9,448.7,172.9}"> </item>
    </section>

    <section name="bigtile"> Big tile
	<item name="id" value="1000"> </item>
 	<item name="xlen" value="414.0"> </item>
	<item name="ylen" value="300.0"> </item>
	<item name="zlen" value="10.0"> </item>
	<item name="x_center" value="12.0"> </item>
	<item name="y_center" value="0.0"> </item>
	<item name="z_center" value="576.7"> located 1 mm above the 4 top tiles</item>
    </section>

   
</AcdGeometry>
