<?xml version="1.0" ?>

<!DOCTYPE acdDigi [
<!ELEMENT acdDigi (section)* >
<!ATTLIST acdDigi cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--    GLAST digi constants
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<acdDigi cvs_Header="$Header$"
         cvs_Revision="$Revision$">

    <section name="acd">  ACD properties
	<item name="lowThreshold"     value="0.2"> MeV enables PHA</item>
        <item name="vetoThreshold"      value="0.4"> MeV nominal veto </item>
        <item name="highThreshold" value="20.0"> MeV CNO </item>
        <item name="adcChannelsPerMeV" value = "203.0793"> conversion from energy to ADC channels </item>
    </section>

</acdDigi>
